gianklug/wearewaylandnow

- layouts/index.html
I'm not aware of a better source to link. The issue is discussed all over the place, but there doesn't seem to be a protocol proposal.
I have:
> Mention global hotkeys and PTT

- layouts/index.html
> feat: add Keypress screencasting section

- layouts/index.html
> feat: add a bunch of fully-functional Wayland native KDE software

- layouts/index.html
> add satty - a screenshot tool inspired by Swappy and Flameshot

- layouts/index.html
Change link for Hyprland to be the Hyprland website instead of its Github repo.
I have:
> Change Hyprland Link to Website

- layouts/index.html
The repository has migrated to Codeberg.
I have:
> Update dwl repository link

- layouts/index.html
> feat: add dotool

- layouts/index.html
> Merge patch from jh-devv

- layouts/index.html
> add clapboard

- layouts/index.html
> Add hyprlock to screen lock tools

- layouts/index.html
> Add shikane to list of display configuration tools

- layouts/index.html
> updated waylock link

- layouts/index.html
> feat: add "GPU Screen Recorder"

- layouts/index.html
Short description of the changes: add niri to "Tiling compositor" section
I have:
> feat: add niri to "Tiling compositor" section

- layouts/index.html
Added Hyprshot as a screenshot tool:
- https://github.com/Gustash/Hyprshot
I have:
> feat: added Hyprshot as a screenshot tool

- layouts/index.html
Added Emote:
- https://github.com/tom-james-watson/Emote
I have:
> feat: added Emote as an emoji handler

- layouts/index.html
Adding nwg-bar to power menu:
- https://github.com/nwg-piotr/nwg-bar
I have:
> feat: added nwg-bar to power menu

- layouts/index.html
Updated displaylink support for GNOME, KDE and Hyprland.
I have:
> feat: displaylink driver for GNOME, KDE and Hyprland

- layouts/index.html
wmenu moved from sr.ht to codeber.org and grim moved from github to sr.ht. I changed links and checked if there is more broken links.
I have:
- [ x] 🤳 made sure that what I am adding is an app for end users, not a developer tool / library (no "wl-clipboard-rs")
- [ x] 🔗 checked that the link I am using refers to the root of the project (example, https://mpv.io) or GitHub repo **if the first is not available**
- [ x] 🤓 checked BOTH the name and the casing of the project(s) I am adding ("GNOME Terminal" and not "gnome-terminal", "bemenu" and not "Bemenu", etc.)
- [ x] 💣 checked that I am using spaces for indentation and that my levels are correct (**no tabs!**)
- [ x] ✋ checked that my section has the correct casing ("My section", and not "My Section")
- [ …
> update link for wmenu and grim

- layouts/index.html
Added ironbar:
- https://github.com/JakeStanger/ironbar
I have:
> feat: added ironbar as a status bar

- layouts/index.html
> feat: added qterminal, pcmanfm-qt, lximage-qt,sfwbar,wshot

- layouts/index.html
Update index.html to include the walker application launcher.
- https://github.com/abenz1267/walker
I have:
> feat: Add walker launcher

- layouts/index.html
Added Thunar as a File manager, gBar as a Status bar and Hyprshade as a Gamma & day/night adjustment tool.
I have:
> add Thunar, gBar and Hyprshade

- layouts/index.html
Add Atril. It's part of MATE, but works just fine standalone. Added a parenthetical about that, too, but I can delete it if needed.
I have:
> Add Atril to list of Wayland PDF viewers

- layouts/index.html
Added hyprsunset (the official blue light filter by hyprland) and hyprpanel ( a highly customizable bar and a notification daemon).
Added Hyprsunset to Gamma & day/ night adjustment tool and Hyprpanel to Status bar.
I have:
> feat: add hyprsunset and hyprpanel

- layouts/index.html
Added a missing comma in the `Widgets` section (after #53)
I have:
> fix: add a missing comma in the `Widgets` section

- layouts/index.html
I suggest to add the [Fabric](https://wiki.ffpy.org/) widgets.
I have:
> Add Fabric Widgets

- layouts/index.html
HDR was just merged into `wayland/wayland-protocol` a day ago, woohoo!
I have:
> Update HDR Info

- layouts/index.html
[nwg-dock-hyprland](https://github.com/nwg-piotr/nwg-dock-hyprland) was excluded from the docks section. Glx-Dock was also not at the top of the list (Docks section was not in alphabetic order.)
I have:
> Add nwg-dock-hyprland to docks section and Glx-Dock / Cairo-Dock

- layouts/index.html
Added Screengrab as it supports Wayland now.
I have:
I opened this file with featherpad and noticed that there are already many tabs present. Probably because the GH web editor defaults to tabs. And yes, there's a tab here too, sorry. A PR which replaces all tabs?
> Added ScreenGrab 3.0

- layouts/index.html
- Replace tabs with whitespaces
- Fix alphabetical ordering
I have:
> Minor fixes

- layouts/index.html
From the previous url:
> Warning: this project has moved to gitlab.freedesktop.org.
> fix: kanshi url

- layouts/index.html
Added new compositors (like pinnacle, scroll, cagebreak etc), Rio terminal, and waypaper.
I have:
> Added new compositors, Rio terminal and waypaper
